### ISSUE TITLE
conflict with tensorflow when installing on win10 using conda

### ISSUE THREAD

**Issue by Heisenberg0391** [Kozea/cairocffi#116]
>conda install -c rmg cairocffi
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - cairocffi
  - tensorflow
Use "conda info <package>" to see the dependencies for each package.

**Comment by liZe** [comment]
The problem is that for some reason, the cairocffi and the tensorflow conda packages are not compatible. I don't know why, but I know that's is something that I can't solve: the "problem" is in the conda packages, not in CairoCFFI.

You have to
- do what "conda info" tells you, or
- ask the managers of conda packages what to do to install both cairocffi and tensorflow.
