### ISSUE TITLE
Is possible to let cairocffi built-in those dlls?

### ISSUE THREAD

**Issue by xy-23** [Kozea/cairocffi#150]
If it's possible, it can greatly reduce the difficulty of installation in Windows.

**Comment by liZe** [comment]
Having built-in dlls in libraries is common on Windows, but it’s not seen as a best practice on other OSes. Moreover, I’m pretty sure that building dlls will only create other problems, because the dll will not work on some systems for some crazy reasons I don’t want to discover.

If someone wants to create a cairocffi-windows package with built-in dlls, it’s OK. But unfortunately I don’t have the time to take care of this, creating a pipeline to automatically build dlls when releasing a new version is too much work for me :unamused:.

[WeasyPrint’s installation guide for Windows](https://weasyprint.readthedocs.io/en/stable/install.html#windows) is currently the best place to find a pretty easy way to install cairo and make it available for cairocffi.
