### ISSUE TITLE
Version numbers are inconsistent.

### ISSUE THREAD

**Issue by merriam** [Kozea/cairocffi#71]
This doesn't seem like it should happen:

```
>>> cairo.cairo_version()
11402
>>> cairo.version
'1.10.0'
>>>
```

Which version is correct?  v1.10.0 or v1.14.02?

**Comment by SimonSapin** [comment]
And don’t forget:

```
>>> cairocffi.VERSION
'0.7.2'
```

They are respectively the version numbers for cairo, pycairo, and cairocffi, which are three separate projects with independent releases.

cairocffi only includes a pycairo version number for compatibility, in case a program or library used it instead of feature detection and cairocffi is used instead. Maybe this wasn’t such a great idea.

But yeah, this all could be better documented.
